export const skills=[
    {
        "name":"c",
        "image":"/skills_logo/c.svg"
    },
    {
        "name":"cpp",
        "image":"/skills_logo/cpp.svg"
    },
    {
        "name":"html",
        "image":"/skills_logo/html.svg"
    },
    {
        "name":"css",
        "image":"/skills_logo/css.svg"
    },
    {
        "name":"Tailwind CSS",
        "image":"/skills_logo/tailwind-css.svg"
    },
    {
        "name":"BootStrap",
        "image":"/skills_logo/bootstrap.svg"
    },
    {
        "name":"javascript",
        "image":"/skills_logo/javascript.svg"
    },
    {
        "name":"React",
        "image":"/skills_logo/react.svg"
    },
    {
        "name":"Node js",
        "image":"/skills_logo/nodejs.svg"
    },
    {
        "name":"Redux",
        "image":"/skills_logo/redux.svg"
    },
    {
        "name":"Mongodb",
        "image":"/skills_logo/mongodb.svg"
    },
    {
        "name":"git",
        "image":"/skills_logo/git.svg"
    },
    {
        "name":"Github",
        "image":"/skills_logo/github.svg"
    },
    {
        "name":"Socket io",
        "image":"/skills_logo/socket-io.svg"
    },
]